import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import FooterComp from "./components/FooterComp";
import { AuthProvider } from "../../context/AuthProvider";

const outfit = Outfit({ subsets: ["latin"], weight: ["400", "500", "600"] });


export const metadata = {
  title: "Shopsy - shop freely",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} antialiased`}
      >
          <AuthProvider>
          <Navbar/>
        {children}
        <FooterComp/>
        </AuthProvider>
      </body>
    </html>
  );
}
